AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - log/**/*
    - tmp/**/*
    - bin/**/*
    - node_modules/**/*
    - db/data_schema.rb
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*

Style/Documentation:
  Enabled: false
